version: "3.5"

services:
  clot-ecommerce-api:
    container_name: clot-ecommerce-api
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - clot-ecommerce-api-db
    restart: on-failure
    command: bash -c "npm run migrate:latest && npm run start:dev"
    environment:
      - PORT=3000
      - DB_HOST=clot-ecommerce-api-db
      - DB_NAME=clot
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_PORT=5432
    volumes:
      - .:/app

  clot-ecommerce-api-db:
    image: postgres
    container_name: clot-ecommerce-api-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=clot
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - clot-ecommerce-api-db:/var/lib/postgresql/data

volumes:
  clot-ecommerce-api-db: